#!/bin/bash
#
# preinstall shell script for bird2
#
SYSCONF_DIR=/usr/local/etc
CONF_FILE=${SYSCONF_DIR}/bird.conf

if [ -f ${CONF_FILE} ] ; then
    echo "A bird configuration exists"
    # detect bird version from conf file
    if grep --q "listen bgp" ${CONF_FILE}; then
         CONF_VERSION=1
    else
         CONF_VERSION=2
    fi
    # if version 1 then we save
    if [ ${CONF_VERSION} == 1 ] ; then
        cp ${CONF_FILE} ${SYSCONF_DIR}/bird.conf.backup
        echo "BIRD Version 1 config file detected, saved to ${SYSCONF_DIR}/bird.conf.backup"
    fi
else
    echo "No bird configuration exists - we are in the clear"
fi
