#! /bin/sh
#
# preinstall shell script for bird2
#
set -e

SYSCONF_DIR=/usr/local/etc
CONF_FILE=${SYSCONF_DIR}/bird.conf

case "$1" in
  install)
    :
    if [ -f ${CONF_FILE} ] ; then
        # detect bird version from conf file
        if grep --q "listen bgp" ${CONF_FILE}; then
             CONF_VERSION=1
        else
             CONF_VERSION=2
        fi
        # if version 1 then we save
        if [ ${CONF_VERSION} == 1 ] ; then
            cp ${CONF_FILE} ${SYSCONF_DIR}/bird.conf.backup
            echo "BIRD Version 1 config file detected, saved to ${SYSCONF_DIR}/bird.conf.backup"
        fi
        echo "BIRD configuration version ${CONF_VERSION} detected."
    else
        echo "No bird configuration exists - we are in the clear"
        exit 0
    fi ;;
  upgrade)
    :

    ;;

  abort-upgrade)
    :

    ;;
  *) exit 0;;
esac

exit 0
